services:
  - type: web
    name: grabi-admin-api
    env: node
    buildCommand: npm ci && npm install dotenv --save
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PORT
        value: 10000
      - key: FIREBASE_PRIVATE_KEY_ID
        value: b0f492dcb4542c080047fc5439040e7502e2608f
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-ntfmj@appdev-86a96.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: 117176618238522617226
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false 